name: Publish APK to GitHub Releases

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build xposed_module debug APK
      run: ./gradlew :xposed_module:assembleDebug

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: xposed_module/build/outputs/apk/debug/xposed_module-debug.apk
        token: ${{ secrets.GITHUB_TOKEN }}
